### ISSUE TITLE
Add rfkelly and chilts as maintainers on npm

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mem#14]
I tried to release a new version using the reverse-backends stuff, but it doesn't look like I've got permissions.  Please add a couple more backend devs to the maintainer list on npm.

**Comment by chilts** [comment]
I was thinking that we wouldn't continue to release it to npm, but instead ust the git repo and relevant hashes. Am just wondering what this gets us (though am also happy if we do continue to release as well). :)

**Comment by rfk** [comment]
Even if we move to using direct git pulls, I'd like to not have old versions sitting around unloved on npm.

**Comment by dannycoates** [comment]
added y'all

**Comment by chilts** [comment]
Yay, @dannycoates is back!
