### ISSUE TITLE
  /account/:id/unlock of a non existent account differs in behavior from fxa-auth-db-mysql

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mem#16]
The MySQL driver succeeds whereas the memory driver fails with a 404 (not found).

Cross filed as https://github.com/mozilla/fxa-auth-db-mysql/issues/11

**Comment by chilts** [comment]
PR for this repo here : https://github.com/mozilla/fxa-auth-db-mem/pull/17

PR for the db-server (tests) here : https://github.com/mozilla/fxa-auth-db-server/pull/124
