### ISSUE TITLE
Travis: This job ran on our legacy infrastructure. Please read our docs on how to upgrade

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-db-mem#41]
Noticed this while bungling my other failure of a PR.

http://docs.travis-ci.com/user/migrating-from-legacy/

Basically we just need to add `sudo: false` to .travis.yml

**Comment by TDA** [comment]
this is actually funny, its almost as if someone sabotaged your PR's :D :D Should I do this? or are you doing it?
