### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-db-mem#8]
Looks like https://github.com/mozilla/fxa-auth-db-mem/blob/ac6538c4e7d92056ae0f4e944a395f6dc8776cd3/package.json#L7 has no `npm test` target defined, plus I don't see a "tests/" directory.

**Comment by chilts** [comment]
Gonna close this since the reverse branch is imminently merging and there's lots and lots of tests there. :)

* https://github.com/mozilla/fxa-auth-db-mem/pull/12
